### ISSUE TITLE
"deno upgrade" is available, but fails

### ISSUE THREAD

**Issue by openjck** [Lukewh/deno-snap#3]
`deno upgrade` fails with the following error:

> error: No such file or directory (os error 2)

I wouldn't normally run this command myself, since Snap takes care of the upgrades, but I happened to notice it by accident.

Since Snap is managing the upgrade, can the "upgrade" sub-command be excluded in the binary that is built?

**Comment by Lukewh** [comment]
I've thought about this and not had time to implement the change. I'm going to make a wrapper script that passes through deno commands as is, unless it's "upgrade" and return a message instead of failing. Thanks for bringing this up 1.5 years ago 😅

**Comment by Lukewh** [comment]
I've now implemented the wrapper, thanks for the report!
