### ISSUE TITLE
Deno.env.get('HOME') returns wrong directory

### ISSUE THREAD

**Issue by alex-skxy** [Lukewh/deno-snap#4]
System: Ubuntu 20.04
Deno version: 1.4.6
When running through snap package, `Deno.env.get('HOME')` returns `/home/<user>/snap/deno/15` instead of `/home/<user>`.

**Comment by Lukewh** [comment]
I've pushed an update to the edge channel `snap refresh --edge deno` that ensures the correct `$HOME` is used.
I'd appreciate any testing. If anything fails, you can revert with `snap refresh --stable deno`.

Branch: https://github.com/Lukewh/deno-snap/tree/redirect-home

**Comment by Lukewh** [comment]
The latest release of the snap addresses this issue
